### pay
POST {{server_host}}/order/edit_state
Content-Type: application/json
Token: {{acess_token}}

{
  "id": "z0krofZ0",
  "state": 2
}

### list
POST {{server_host}}/order/list
Content-Type: application/json
Token: {{acess_token}}

{
  "page": "",
  "size": "",
  "param": {
    "username": "",
    "id": "",
    "userId": "EoewKcJc",
    "state": "0"
  }
}

### edit_state
POST {{server_host}}/order/edit_state
Content-Type: application/json
Token: {{acess_token}}

{
  "id": "z0krofZ0",
  "state": "1"
}

### edit_state2
POST {{server_host}}/order/edit_state
Content-Type: application/json
Token: {{acess_token}}

{
  "id": "z0krofZ0",
  "state": "2"
}


