### login接口测试
### 正常登入
POST {{server_host}}/user/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "admin",
  "password": "1234abcd@"
}

### 是否为空判断
### 用户名为空
POST {{server_host}}/user/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "",
  "password": "1234abcd@"
}

### 密码为空判断
POST {{server_host}}/user/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "admin",
  "password": ""
}

### 密码错误登入
POST {{server_host}}/user/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "admin",
  "password": "1234abcd"
}

### 账号错误登入
POST {{server_host}}/user/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "admi",
  "password": "1234abcd@"
}

### 账号错误登入
POST {{server_host}}/user/login
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "admi",
  "password": "1234abcd@"
}

### regist测试
### 正常注册
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "test0916",
  "password": "1234abcd@",
  "phone": "13111111111"
}

### 用户名为空
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "",
  "password": "1234abcd@",
  "phone": "13111111111"
}

### 密码为空判断
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "test0917",
  "password": "",
  "phone": "13111111111"
}

### 手机为空判断
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "test0917",
  "password": "12345abc",
  "phone": ""
}

### 密码长度判断
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "test0917",
  "password": "12",
  "phone": "13111111111"
}

### 密码长度判断2
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "test0917",
  "password": "123456789000000000000000000000000000000000000000000000000000000000000000000000000000000000000000022222222222222222222222222222222222222222222222",
  "phone": "13111111111"
}

### 手机格式
POST {{server_host}}/user/register
Content-Type: application/json

{
  "username": "test0917",
  "password": "123456789",
  "phone": "13111"
}

### check_login
POST {{server_host}}/user/check_login
Token: IMeFaRWW
Content-Type: application/json

{
  "token": "IMeFaRWW"
}


### list
POST {{server_host}}/user/list
token: IMeFaRWW
Content-Type: application/json

{
  "page": "1",
  "size": "10",
  "param": {
    "id": "",
    "username": "",
    "roleId": "2"
  }
}


### save
POST {{server_host}}/user/save
Content-Type:application/json
Token:IMeFaRWW

{
  "headPic": "20240608/1717817487942.jpg",
  "id": "",
  "password": "test2123456",
  "phone": "13700000001",
  "rate": 0,
  "roleId": 1,
  "sex": 3,
  "token": "IMeFaRWW",
  "username": "test3"
}
### 冲突手机号
POST {{server_host}}/user/save
Content-Type:application/json
Token:IMeFaRWW

{
  "headPic": "20240608/1717817487942.jpg",
  "id": "",
  "password": "test2123456",
  "phone": "13700000000",
  "rate": 0,
  "roleId": 1,
  "sex": 3,
  "token": "IMeFaRWW",
  "username": "test3"
}
### 冲突用户名
POST {{server_host}}/user/save
Content-Type:application/json
Token:IMeFaRWW

{
  "headPic": "20240608/1717817487942.jpg",
  "id": "",
  "password": "test2123456",
  "phone": "13700000003",
  "rate": 0,
  "roleId": 1,
  "sex": 3,
  "token": "IMeFaRWW",
  "username": "test3"
}

### delete
POST {{server_host}}/user/delete
Content-Type: application/json
Token: {{acess_token}}

{
  "id": "7BQT1JIg",
  "token": "{{acess_token}}"
}


